### ISSUE TITLE
Image rendering via picture.js doesn't work

### ISSUE THREAD

**Issue by adrivn** [eastslopestudio/eleventy-starter#15]
Hello Ryan! Thanks for all the work you (and the rest of the contributors) put into this starter, it certainly has a lot of potential.

Whenever I try to render images in Markdown (using the `![Alt-tag](image.jpg)` syntax I get the following error:

`Uncaught exception: (more in DEBUG output)
> Input file is missing
>
>`Error` was thrown:
 >   Error: Input file is missing
 >      at Function.module.exports.loopWhile (C:\Playground\StaticSites\eleventy-starter\node_modules\deasync\index.js:71:23)
>        at deasyncSharp (C:\Playground\StaticSites\eleventy-starter\utils\picture.js:36:11)
>        at module.exports (C:\Playground\StaticSites\eleventy-starter\utils\picture.js:104:33)
>        at Object.md.renderer.rules.image (C:\Playground\StaticSites\eleventy-starter\utils\markdown.js:42:14)
>        at Renderer.renderInline (C:\Playground\StaticSites\eleventy-starter\node_modules\markdown-it\lib\renderer.js:271:28)
>        at Renderer.render (C:\Playground\StaticSites\eleventy-starter\node_modules\markdown-it\lib\renderer.js:324:22)
>        at MarkdownIt.render (C:\Playground\StaticSites\eleventy-starter\node_modules\markdown-it\lib\index.js:543:24)
>        at C:\Playground\StaticSites\eleventy-starter\node_modules\@11ty\eleventy\src\Engines\Markdown.js:72:38
>        at processTicksAndRejections (internal/process/task_queues.js:97:5)
>        at async Template.render (C:\Playground\StaticSites\eleventy-starter\node_modules\@11ty\eleventy\src\TemplateContent.js:199:22)`

What am I doing wrong?

**Comment by adrivn** [comment]
I fixed it.

It was just updating the .config.js file and modifying the 'media' variable to indicate the actual path to the images folder, and everything ran smoothly afterwards.
